# Generated by Django 3.2.8 on 2021-11-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idAlumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
                ('correo', models.TextField(max_length=50)),
                ('codigo', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('idProfesor', models.AutoField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
                ('correo', models.TextField(max_length=50)),
                ('codigo', models.TextField(max_length=10)),
                ('calificacion', models.SmallIntegerField()),
                ('materia', models.TextField(max_length=6)),
            ],
        ),
    ]
