# Generated by Django 3.2.8 on 2021-11-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='idProfesor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
