# Generated by Django 3.2.9 on 2021-11-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
