# Generated by Django 3.2.9 on 2021-11-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_alumno_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=30)),
                ('clave', models.TextField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='materia',
        ),
        migrations.AddField(
            model_name='profesor',
            name='materia',
            field=models.ManyToManyField(to='webapp.Materia'),
        ),
    ]
