# Generated by Django 3.2.8 on 2021-11-22 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20211117_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='nombre',
        ),
    ]
