# Generated by Django 3.2.8 on 2021-11-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_materia_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='calificacion',
        ),
        migrations.AlterField(
            model_name='profesor',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
