# Generated by Django 3.2.8 on 2021-11-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_materia_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
