# Generated by Django 3.2.8 on 2021-11-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_profesor_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
