# Generated by Django 3.2.9 on 2021-11-24 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20211123_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='webapp.profesor'),
        ),
    ]
