# Generated by Django 3.2.8 on 2021-11-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20211123_0017'),
        ('webapp', '0011_alter_comentario_profesor'),
    ]

    operations = [
    ]
