# Generated by Django 3.2.9 on 2021-11-26 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_comentario_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='alumno',
        ),
    ]
