# Generated by Django 3.2.9 on 2021-11-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_remove_comentario_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='horario',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='materia',
            name='nombre',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='materia',
            name='salon',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
