# Generated by Django 3.2.9 on 2021-11-29 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_merge_20211126_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.profesor'),
        ),
    ]
