# Generated by Django 3.2.9 on 2021-11-30 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_comentario_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('puntualidad', models.IntegerField()),
                ('dificultad', models.IntegerField()),
                ('dominioDelTema', models.IntegerField()),
                ('facilidad', models.IntegerField()),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='webapp.profesor')),
            ],
        ),
    ]
